services:
  9router:
    image: ghcr.io/vanszs/vansrouter:0.8.6
    container_name: vansrouter-086-prod
    restart: always
    ports:
      - "20127:20128"
    volumes:
      - /root/.openclaw/workspace/.vansroute:/app/data
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      PORT: "20128"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
