export default {
  id: "vyce",
  priority: 55,
  hasFree: true,
  alias: "vyce",
  aliases: ["vy"],
  uiAlias: "vyce",
  display: {
    name: "Vyce AI",
    icon: "bolt",
    color: "#8B5CF6",
    textIcon: "VY",
    website: "https://vyceai.com",
    notice: {
      text: "$50 free credits. OpenAI-compatible proxy. Note: models are masked (gemini→GPT-4o, deepseek→DeepSeek-V3).",
      apiKeyUrl: "https://vyceai.com/dashboard",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://vyceai.com/v1/chat/completions",
    validateUrl: "https://vyceai.com/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "auto", name: "Auto (routes to best)" },
    { id: "gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite (masked → GPT-4o)" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash (masked → DeepSeek-V3)" },
    { id: "gemini-3.6-flash", name: "Gemini 3.6 Flash" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6 (verified only)" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5 (verified only)" },
    { id: "claude-opus-5", name: "Claude Opus 5 (verified only)" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "grok-4.6", name: "Grok 4.6" },
    { id: "grok-4.5", name: "Grok 4.5" },
    { id: "nemotron-ultra-550b", name: "Nemotron Ultra 550B" },
    { id: "nemotron-vision", name: "Nemotron Vision" },
  ],
};
